apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx
  - traefik-helm.yaml
  - traefik/application.yaml
  - external-dns/application.yaml
  - cert-manager/application.yaml
  - cert-manager/clusterissuers-application.yaml
  - traefik-middleware/application.yaml
  - local-path-provisioner/
#  - authentik-dependencies/application.yaml
  - authentik/application.yaml
  - silverbullet/application.yaml
